### ISSUE TITLE
Delete the yarn.lock, yarn, yarn start, it fails to run

### ISSUE THREAD

**Issue by sgehrman** [blocknative/react-demo#220] opened 2022-07-29 03:07 UTC
Delete the yarn.lock, yarn, yarn start, it fails to run

**Comment by Adamj1232** [comment] 2022-07-29 14:30
@sgehrman I just cloned a fresh version, ran `yarn` and `yarn start` and the program started without issue.
Can you please provide more information on the issue you are seeing? Errors in the console?

**Comment by ryana** [comment] 2022-07-29 19:20
I think the issue is that you shouldn't be deleting `yarn.lock`. I'm used to seeing that file checked into source control for a reason. If there is the need to update deps in the `yarn.lock`, it should happen on a case-by-case basis.

Is there a reason you need to delete the `yarn.lock`?

**Comment by Adamj1232** [comment] 2022-08-01 15:34
Closing as deleting the yarn.lock is not part of an expected cloning/starting process

**Closed by Adamj1232** 2022-08-01 15:34 UTC
